services:
  app:
    container_name: cyber-suite-app
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - .env
  
  nginx:
    container_name: cyber-suite-nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - app
    restart: always
